// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

function eq__001($$class) {
  var ids = CamlinternalOO.get_method_labels($$class, [
        "notEqual",
        "equal"
      ]);
  var notEqual = ids[0];
  var equal = ids[1];
  CamlinternalOO.set_method($$class, notEqual, (function (self$1, a, b) {
          return !Curry._3(self$1[0][equal], self$1, a, b);
        }));
  return (function (env, self) {
      return CamlinternalOO.create_object_opt(self, $$class);
    });
}

var eq_ = /* class */[
  undefined,
  eq__001,
  undefined,
  undefined
];

exports.eq_ = eq_;
/* No side effect */
