// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

function monoid__001($$class) {
  CamlinternalOO.get_method_labels($$class, [
        "mempty",
        "mappend"
      ]);
  return (function (env, self) {
      return CamlinternalOO.create_object_opt(self, $$class);
    });
}

var monoid_ = /* class */[
  undefined,
  monoid__001,
  undefined,
  undefined
];

exports.monoid_ = monoid_;
/* No side effect */
