// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

function num_001($$class) {
  CamlinternalOO.get_method_labels($$class, [
        "subtract",
        "negate",
        "multiply",
        "add"
      ]);
  return (function (env, self) {
      return CamlinternalOO.create_object_opt(self, $$class);
    });
}

var num = /* class */[
  undefined,
  num_001,
  undefined,
  undefined
];

exports.num = num;
/* No side effect */
