// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function Newtype0(T) {
  return { };
}

function Newtype1(T) {
  return { };
}

function Newtype2(T) {
  return { };
}

function Newtype3(T) {
  return { };
}

function Newtype4(T) {
  return { };
}

function Newtype5(T) {
  return { };
}

function Newtype6(T) {
  return { };
}

exports.Newtype0 = Newtype0;
exports.Newtype1 = Newtype1;
exports.Newtype2 = Newtype2;
exports.Newtype3 = Newtype3;
exports.Newtype4 = Newtype4;
exports.Newtype5 = Newtype5;
exports.Newtype6 = Newtype6;
/* No side effect */
